version: '3.7'
services:
    redis:
        container_name: redis
        image: redis:6.2.6
        command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
        # command: redis-server --save "" --appendonly no --requirepass ${REDIS_PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - redis_data:/data
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always

    redis-commander:
        container_name: redis-commander
        image: rediscommander/redis-commander
        ports:
            - 8081:8081
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - REDIS_PASSWORD=${REDIS_PASSWORD}
            - HTTP_USER=${HTTP_USER}
            - HTTP_PASSWORD=${HTTP_PASSWORD}
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always

    redis-stat:
        container_name: redis-stat
        image: insready/redis-stat
        command: --server redis:6379/${REDIS_PASSWORD}
        ports:
            - 8082:63790
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always

volumes:
    redis_data:

networks:
    webnet:
        name: webnet
        driver: bridge
