version: '3.7'
services:
    redis:
        container_name: redis
        image: redis:5.0.7
        command: redis-server --save "" --appendonly no
        ports:
            - 6379:6379
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
