version: '3.7'
services:
    redis:
        container_name: redis
        image: redis:6.0.9
        command: redis-server --save "" --appendonly no --requirepass ${PASSWORD}
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
        networks:
            - webnet
        logging:
            driver: 'json-file'
            options:
                max-size: '8m'
                max-file: '10'
        restart: always
networks:
    webnet:
        name: webnet
        driver: bridge
